baseURL = ''
languageCode = 'en-us'
title = "ACCC-GT-CCF Linktree"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "Linktree for accc-gt-ccf"
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]

[taxonomies]
  tag = ""
  category = ""
